-- ---------------------------------------------------------------------------
-- V001 : 사용자
--   * 인증은 Cognito 가 담당하므로 비밀번호 관련 열은 두지 않는다.
--   * 내부 PK 는 bigint, 외부 노출 식별자는 uuid public_id 를 사용한다.
--   * 모든 시각은 timestamptz(UTC) 로 저장한다.
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     uuid         NOT NULL DEFAULT gen_random_uuid(),
    cognito_sub   varchar(255) NOT NULL,
    email         varchar(255) NOT NULL,
    display_name  varchar(100),
    status        varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    timezone      varchar(64)  NOT NULL DEFAULT 'Asia/Seoul',
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uk_users_public_id   UNIQUE (public_id),
    CONSTRAINT uk_users_cognito_sub UNIQUE (cognito_sub),
    CONSTRAINT ck_users_status      CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

COMMENT ON TABLE  users              IS '서비스 이용자. Cognito sub 로 식별한다.';
COMMENT ON COLUMN users.public_id    IS 'API 로 노출하는 식별자. 순차 ID 추측을 방지한다.';
COMMENT ON COLUMN users.cognito_sub  IS 'Cognito JWT 의 sub 클레임.';
