-- ---------------------------------------------------------------------------
-- V003 : PC 등록·연결
--
--   devices                  등록된 PC. 소유권 판정과 기기 인증의 기준이 된다.
--   device_capabilities      PC 가 어떤 기능을 지원하는지 (실행 가능 여부 판정)
--   device_pairing_requests  5분·1회용 등록 코드
--
--   FK 순서 때문에 devices 를 먼저 만든다.
--   (device_pairing_requests.consumed_device_id 가 devices 를 참조)
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- devices
-- ---------------------------------------------------------------------------
CREATE TABLE devices (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      uuid         NOT NULL DEFAULT gen_random_uuid(),
    user_id        bigint       NOT NULL,
    name           varchar(100) NOT NULL,
    -- Ed25519 공개키(Base64). 개인키는 사용자 PC 밖으로 나오지 않는다. (문서 LA-01)
    public_key     text         NOT NULL,
    os             varchar(20)  NOT NULL,
    -- 실행 패키지와 플랫폼 호환성 판정에 사용한다. Agent 등록 시 필수로 보고한다.
    architecture   varchar(20)  NOT NULL,
    os_version     varchar(50),
    agent_version  varchar(50),
    status         varchar(20)  NOT NULL DEFAULT 'OFFLINE',
    last_seen_at   timestamptz,
    revoked_at     timestamptz,
    -- 낙관적 잠금. 조회 응답의 ETag 로 사용해 낡은 화면의 덮어쓰기를 막는다. (문서 3.4.4)
    version        integer      NOT NULL DEFAULT 0,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT fk_devices_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT uk_devices_public_id UNIQUE (public_id),

    -- 같은 공개키로 다른 기기가 위장 등록하는 것을 막는다.
    CONSTRAINT uk_devices_public_key UNIQUE (public_key),

    CONSTRAINT ck_devices_os
        CHECK (os IN ('WINDOWS', 'MACOS')),

    CONSTRAINT ck_devices_architecture
        CHECK (architecture IN ('X86_64', 'ARM64')),

    CONSTRAINT ck_devices_status
        CHECK (status IN ('ONLINE', 'READY', 'BUSY', 'OFFLINE', 'REVOKED')),

    -- REVOKED 상태에는 해제 시각이 있어야 한다.
    CONSTRAINT ck_devices_revoked_at
        CHECK ((status = 'REVOKED') = (revoked_at IS NOT NULL))
);

-- 내 PC 목록 조회와 READY 확인
CREATE INDEX idx_devices_user_status ON devices (user_id, status);

CREATE TRIGGER trg_devices_set_updated_at
    BEFORE UPDATE ON devices
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  devices            IS '등록된 PC. 로컬 에이전트가 설치된 기기.';
COMMENT ON COLUMN devices.public_key IS 'Ed25519 공개키. 연결마다 도전값 서명을 검증하는 데 사용한다.';
COMMENT ON COLUMN devices.version    IS '낙관적 잠금 값. API 의 ETag 로 노출한다.';

-- ---------------------------------------------------------------------------
-- device_capabilities
--   Agent 가 READY 프레임에서 보고한 지원 기능.
--   명령 전송 전 "이 PC 가 이 작업을 할 수 있는가" 판정에 사용한다. (문서 DV-05)
-- ---------------------------------------------------------------------------
CREATE TABLE device_capabilities (
    device_id   bigint      NOT NULL,
    task_type   varchar(30) NOT NULL,
    available   boolean     NOT NULL DEFAULT true,
    reported_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_device_capabilities PRIMARY KEY (device_id, task_type),

    CONSTRAINT fk_device_capabilities_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE,

    -- Agent 가 실제로 실행할 수 있는 작업 유형만 허용한다.
    -- 처리 경로가 LOCAL_AGENT 인 TaskType 과 일치한다.
    -- 새 작업 유형을 Agent 에 추가하면 이 목록도 함께 늘려야 한다.
    CONSTRAINT ck_device_capabilities_task_type
        CHECK (task_type IN ('FILE_SEARCH', 'SYSTEM_STATUS', 'CODE_ANALYSIS', 'AI_AGENT_USAGE'))
);

COMMENT ON TABLE  device_capabilities           IS 'Agent 가 READY 프레임의 supportedTaskTypes 로 보고한 지원 작업 유형.';
COMMENT ON COLUMN device_capabilities.task_type IS 'TaskType 값. PK 가 (device_id, task_type) 이라 최신 보고로 덮어쓴다.';

-- ---------------------------------------------------------------------------
-- device_pairing_requests
--   5분·1회용 등록 코드. 코드 원문은 저장하지 않고 해시만 보관한다. (문서 DV-01)
-- ---------------------------------------------------------------------------
CREATE TABLE device_pairing_requests (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          uuid         NOT NULL DEFAULT gen_random_uuid(),
    user_id            bigint       NOT NULL,
    -- 코드 원문 저장 금지. 대조는 해시 비교로 한다.
    code_hash          varchar(255) NOT NULL,
    status             varchar(20)  NOT NULL DEFAULT 'PENDING',
    expires_at         timestamptz  NOT NULL,
    consumed_at        timestamptz,
    consumed_device_id bigint,
    created_at         timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT fk_pairing_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT fk_pairing_consumed_device
        FOREIGN KEY (consumed_device_id) REFERENCES devices (id) ON DELETE SET NULL,

    CONSTRAINT uk_pairing_public_id UNIQUE (public_id),

    CONSTRAINT ck_pairing_status
        CHECK (status IN ('PENDING', 'COMPLETED', 'EXPIRED')),

    -- 만료 시각은 생성 시각보다 뒤여야 한다. (문서 2.7)
    CONSTRAINT ck_pairing_expires_after_created
        CHECK (expires_at > created_at),

    -- 사용 완료 상태에는 사용 시각이 있어야 한다.
    --
    -- consumed_device_id 는 조건에 넣지 않는다.
    -- 기기를 삭제하면 FK 의 ON DELETE SET NULL 이 이 열을 NULL 로 바꾸는데,
    -- NOT NULL 을 요구하면 그 UPDATE 가 제약에 걸려 기기 삭제 자체가 실패한다.
    CONSTRAINT ck_pairing_consumed
        CHECK (
            (status = 'COMPLETED' AND consumed_at IS NOT NULL)
            OR (status <> 'COMPLETED' AND consumed_at IS NULL AND consumed_device_id IS NULL)
        )
);

-- 사용자별 활성 코드는 한 건으로 제한한다. (문서 2.1.1 "사용자별 활성 코드 수 제한")
--
-- 주의: 시간이 지나도 status 는 자동으로 바뀌지 않는다.
--       만료된 PENDING 행이 남아 있으면 새 코드를 발급할 수 없으므로,
--       발급 서비스는 반드시 같은 트랜잭션에서 기존 활성 코드를 먼저 무효화해야 한다.
--
--         UPDATE device_pairing_requests SET status = 'EXPIRED'
--          WHERE user_id = ? AND status = 'PENDING';
--         INSERT INTO device_pairing_requests (...) VALUES (...);
--
--       인덱스 조건에 expires_at > now() 를 넣을 수는 없다. now() 가 IMMUTABLE 이 아니다.
CREATE UNIQUE INDEX uk_pairing_active_per_user
    ON device_pairing_requests (user_id)
    WHERE status = 'PENDING';

-- 만료 처리 배치가 사용할 조회
CREATE INDEX idx_pairing_pending_expires
    ON device_pairing_requests (expires_at)
    WHERE status = 'PENDING';

COMMENT ON TABLE  device_pairing_requests           IS '5분·1회용 PC 등록 코드.';
COMMENT ON COLUMN device_pairing_requests.code_hash IS '등록 코드의 해시. 원문은 어떤 경우에도 저장하지 않는다.';
