-- ---------------------------------------------------------------------------
-- V004 : 사용자 요청 원장
--
--   tasks                사용자 요청의 최종 원장. API 가 반환하는 taskId 의 기준.
--   task_events          상태 전이 타임라인. WSS 가 끊겨도 REST 로 복구한다.
--   idempotency_records  중복 클릭·HTTP 재전송으로 인한 작업 중복 방지.
--
--   시각 열은 timestamptz 를 쓰고 Session 시간대는 Asia/Seoul 로 통일한다.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- tasks
-- ---------------------------------------------------------------------------
CREATE TABLE tasks (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        uuid         NOT NULL DEFAULT gen_random_uuid(),
    user_id          bigint       NOT NULL,

    -- 처리 경로가 LOCAL_AGENT 일 때만 채워진다.
    -- 기기 등록 해제는 행 삭제가 아니라 status = 'REVOKED' 로 처리하므로 RESTRICT 로 둔다.
    device_id        bigint,

    -- 사용자가 입력한 원문. 분석 전에도 요청을 추적할 수 있도록 먼저 저장한다.
    input_text       text         NOT NULL,
    -- 이력 목록에 표시할 짧은 요약
    request_summary  text,

    -- 분석 전에는 NULL 이고, NLU 응답을 검증한 뒤에 채워진다.
    task_type        varchar(30),
    processing_route varchar(20),

    status           varchar(30)  NOT NULL DEFAULT 'CREATED',

    -- NLU 가 추출하고 API 가 재검증한 작업 입력값
    parameters       jsonb,
    -- 작업 유형별 최종 결과
    result           jsonb,
    -- 실패·만료 시의 ErrorCode 값
    error_code       varchar(40),

    -- 프론트에서 Agent·LLM 까지 한 요청을 추적하는 식별자
    correlation_id   uuid,

    version          integer      NOT NULL DEFAULT 0,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now(),
    completed_at     timestamptz,

    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT fk_tasks_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE RESTRICT,

    CONSTRAINT uk_tasks_public_id UNIQUE (public_id),

    -- agent_dispatches 가 (task_id, device_id) 복합 FK 로 참조한다.
    -- 작업의 대상 기기와 실제 전달 기기가 어긋나는 것을 DB 에서 막기 위한 참조 대상이다.
    CONSTRAINT uk_tasks_id_device UNIQUE (id, device_id),

    CONSTRAINT ck_tasks_status
        CHECK (status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION', 'WAITING_FOR_DEVICE',
                          'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED')),

    CONSTRAINT ck_tasks_task_type
        CHECK (task_type IS NULL OR task_type IN ('WEATHER_LOOKUP', 'FILE_SEARCH', 'SYSTEM_STATUS',
                                                  'TEXT_SUMMARY', 'CODE_ANALYSIS', 'AI_AGENT_USAGE')),

    CONSTRAINT ck_tasks_processing_route
        CHECK (processing_route IS NULL OR processing_route IN ('BACKEND_SERVICE', 'LOCAL_AGENT', 'LLM_SERVICE')),

    -- 로컬 실행 작업에는 대상 기기가 반드시 있어야 한다.
    CONSTRAINT ck_tasks_local_agent_requires_device
        CHECK (processing_route IS DISTINCT FROM 'LOCAL_AGENT' OR device_id IS NOT NULL),

    -- 완료 시각은 최종 상태일 때만 존재한다.
    CONSTRAINT ck_tasks_completed_at
        CHECK ((status IN ('SUCCEEDED', 'FAILED', 'EXPIRED')) = (completed_at IS NOT NULL)),

    -- 오류 코드는 실패·만료일 때만 존재한다.
    CONSTRAINT ck_tasks_error_code
        CHECK (error_code IS NULL OR status IN ('FAILED', 'EXPIRED')),

    -- 성공 결과와 오류 코드가 동시에 존재하지 않는다.
    CONSTRAINT ck_tasks_result_or_error
        CHECK (result IS NULL OR error_code IS NULL),

    -- P0 결과 크기 상한. Agent 가 limit·truncated 로 먼저 줄이지만
    -- 구현 오류나 변조로 큰 결과가 올라오는 것을 DB 에서 막는다.
    CONSTRAINT ck_tasks_result_size
        CHECK (result IS NULL OR octet_length(result::text) <= 65536)
);

-- 최신순 이력 커서 목록 (GET /history)
CREATE INDEX idx_tasks_user_created ON tasks (user_id, created_at DESC, id DESC);

-- 기기별 실행 중 작업 확인 (동시 작업 1건 판정)
CREATE INDEX idx_tasks_device_status ON tasks (device_id, status)
    WHERE device_id IS NOT NULL;

CREATE TRIGGER trg_tasks_set_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  tasks                  IS '사용자 요청의 최종 원장. 즉시 완료 가능한 요청도 이력 일관성을 위해 생성한다.';
COMMENT ON COLUMN tasks.device_id        IS '기기 등록 해제는 행 삭제가 아니라 devices.status = REVOKED 로 처리한다.';
COMMENT ON COLUMN tasks.result           IS '작업 유형별 최종 결과. 64KB 상한.';
COMMENT ON COLUMN tasks.correlation_id   IS '프론트→API→NLU·LLM·Agent 전체 추적 식별자.';

-- ---------------------------------------------------------------------------
-- task_events
--   상태 변경 타임라인. 상태 전이와 같은 트랜잭션에서 기록한다.
-- ---------------------------------------------------------------------------
CREATE TABLE task_events (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   uuid        NOT NULL DEFAULT gen_random_uuid(),
    task_id     bigint      NOT NULL,

    -- 같은 밀리초에 여러 이벤트가 생길 수 있어 occurred_at 만으로는 순서를 정할 수 없다.
    -- API 에는 노출하지 않고 커서 페이징의 정렬 기준으로만 사용한다.
    -- 채번은 tasks 행을 FOR UPDATE 로 잠근 뒤 MAX(sequence) + 1 로 한다.
    sequence    integer     NOT NULL,

    -- 최초 생성 이벤트는 이전 상태가 없다.
    from_status varchar(30),
    to_status   varchar(30) NOT NULL,

    -- 실패·대기·거부의 고정 사유 코드 (ErrorCode 또는 ACK reasonCode)
    reason_code varchar(40),
    -- 사용자에게 표시할 설명. 민감정보를 넣지 않는다.
    message     text,

    occurred_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_task_events_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

    CONSTRAINT uk_task_events_public_id UNIQUE (public_id),

    -- 이벤트 순서 중복 방지
    CONSTRAINT uk_task_events_sequence UNIQUE (task_id, sequence),

    CONSTRAINT ck_task_events_sequence CHECK (sequence >= 1),

    CONSTRAINT ck_task_events_from_status
        CHECK (from_status IS NULL OR from_status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION',
               'WAITING_FOR_DEVICE', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED')),

    CONSTRAINT ck_task_events_to_status
        CHECK (to_status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION', 'WAITING_FOR_DEVICE',
               'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED')),

    -- 같은 상태로의 전이는 기록하지 않는다.
    CONSTRAINT ck_task_events_transition
        CHECK (from_status IS DISTINCT FROM to_status)
);

COMMENT ON TABLE  task_events          IS '작업 상태 전이 타임라인. WSS 단절 후 REST 로 복구하는 근거가 된다.';
COMMENT ON COLUMN task_events.sequence IS 'API 미노출. 커서 페이징 정렬 기준. tasks 행 잠금 후 MAX + 1 로 채번한다.';

-- ---------------------------------------------------------------------------
-- idempotency_records
--   같은 Idempotency-Key 로 다시 요청하면 기존 Task 를 그대로 반환한다.
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_records (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint       NOT NULL,
    idempotency_key varchar(100) NOT NULL,
    request_path    varchar(200) NOT NULL,

    -- 같은 키에 다른 본문이 오면 IDEMPOTENCY_CONFLICT 로 거부하기 위한 값
    request_hash    varchar(64)  NOT NULL,

    task_id         bigint       NOT NULL,
    response_status integer,
    expires_at      timestamptz  NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT fk_idempotency_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT fk_idempotency_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

    -- 사용자·키·경로 조합으로 중복을 판정한다.
    CONSTRAINT uk_idempotency_scope
        UNIQUE (user_id, idempotency_key, request_path),

    CONSTRAINT ck_idempotency_expires_after_created
        CHECK (expires_at > created_at)
);

-- 만료 레코드 정리 배치용
CREATE INDEX idx_idempotency_expires ON idempotency_records (expires_at);

COMMENT ON TABLE  idempotency_records              IS '작업 생성 중복 방지. 보존 기간은 24시간.';
COMMENT ON COLUMN idempotency_records.request_hash IS '요청 본문 해시. 같은 키에 다른 본문이면 409 로 거부한다.';
