-- ---------------------------------------------------------------------------
-- V005 : 로컬 에이전트 작업 전달
--
--   Spring Pod 가 바뀌거나 WSS 가 끊겨도 미완료 전달을 다시 보낼 수 있도록
--   전달 시도를 원장으로 남긴다.
--
--   Task 당 활성 전달 한 건, 기기당 동시 작업 한 건을 부분 UNIQUE 로 강제한다.
-- ---------------------------------------------------------------------------

CREATE TABLE agent_dispatches (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       uuid        NOT NULL DEFAULT gen_random_uuid(),

    task_id         bigint      NOT NULL,
    device_id       bigint      NOT NULL,

    status          varchar(20) NOT NULL DEFAULT 'PENDING',

    -- 재연결 재전송 횟수
    attempt_count   integer     NOT NULL DEFAULT 0,

    -- Agent 가 이 시각을 지나면 실행하지 않는다.
    expires_at      timestamptz NOT NULL,

    dispatched_at   timestamptz,
    acknowledged_at timestamptz,
    completed_at    timestamptz,

    -- Agent 가 거부하거나 실행에 실패한 사유 (ACK.reasonCode / RESULT.error.code)
    reason_code     varchar(40),

    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    -- 작업의 대상 기기와 실제 전달 기기가 반드시 같아야 한다.
    --
    -- task_id 와 device_id 를 따로 참조하면, 서비스 코드의 실수로 A 사용자의 작업이
    -- B 사용자의 PC 로 전달돼도 DB 가 막지 못한다. 소유권 격리(DV-04) 위반이므로
    -- 복합 FK 로 두 값이 어긋나는 것을 원천 차단한다.
    CONSTRAINT fk_dispatch_task_device
        FOREIGN KEY (task_id, device_id) REFERENCES tasks (id, device_id) ON DELETE CASCADE,

    -- 기기 등록 해제는 devices.status = 'REVOKED' 로 처리하므로 이력을 보존한다.
    CONSTRAINT fk_dispatch_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE RESTRICT,

    CONSTRAINT uk_dispatch_public_id UNIQUE (public_id),

    CONSTRAINT ck_dispatch_status
        CHECK (status IN ('PENDING', 'DISPATCHED', 'ACKNOWLEDGED', 'COMPLETED', 'FAILED', 'EXPIRED')),

    CONSTRAINT ck_dispatch_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_dispatch_expires_after_created
        CHECK (expires_at > created_at),

    -- 완료 시각은 최종 상태일 때만 존재한다.
    CONSTRAINT ck_dispatch_completed_at
        CHECK ((status IN ('COMPLETED', 'FAILED', 'EXPIRED')) = (completed_at IS NOT NULL)),

    -- 사유 코드는 실패·만료일 때만 존재한다.
    CONSTRAINT ck_dispatch_reason_code
        CHECK (reason_code IS NULL OR status IN ('FAILED', 'EXPIRED'))
);

-- ---------------------------------------------------------------------------
-- 활성 전달 제한
--
--   주의: V003 의 등록 코드와 같은 함정이 있다.
--         시간이 지나도 status 는 자동으로 바뀌지 않으므로, 만료된 활성 전달이
--         남아 있으면 그 Task·기기가 영구히 막힌다.
--
--         만료 처리 배치가 expires_at 이 지난 PENDING·DISPATCHED·ACKNOWLEDGED 를
--         주기적으로 EXPIRED 로 바꿔야 한다. (idx_dispatch_active_expires 사용)
--
--         인덱스 조건에 expires_at > now() 를 넣을 수는 없다. now() 가 IMMUTABLE 이 아니다.
-- ---------------------------------------------------------------------------

-- Task 당 활성 전달은 한 건. 같은 작업이 두 번 전달되는 것을 막는다.
CREATE UNIQUE INDEX uk_dispatch_active_task
    ON agent_dispatches (task_id)
    WHERE status IN ('PENDING', 'DISPATCHED', 'ACKNOWLEDGED');

-- 기기당 동시 작업은 한 건. (P0 규칙, DEVICE_BUSY 판정 근거)
CREATE UNIQUE INDEX uk_dispatch_active_device
    ON agent_dispatches (device_id)
    WHERE status IN ('PENDING', 'DISPATCHED', 'ACKNOWLEDGED');

-- 재연결 시 미완료 전달 조회
CREATE INDEX idx_dispatch_device_status ON agent_dispatches (device_id, status);

-- 만료 처리 배치용
CREATE INDEX idx_dispatch_active_expires
    ON agent_dispatches (expires_at)
    WHERE status IN ('PENDING', 'DISPATCHED', 'ACKNOWLEDGED');

CREATE TRIGGER trg_agent_dispatches_set_updated_at
    BEFORE UPDATE ON agent_dispatches
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  agent_dispatches               IS 'Agent 작업 전달 시도. 연결 복구 뒤 미완료 전달을 다시 보내는 근거가 된다.';
COMMENT ON COLUMN agent_dispatches.attempt_count IS '재연결 재전송 횟수.';
COMMENT ON COLUMN agent_dispatches.reason_code   IS 'Agent 가 거부·실패한 사유. ACK.reasonCode 또는 RESULT.error.code 값.';
