-- ---------------------------------------------------------------------------
-- V006 : 비동기 LLM 작업과 Outbox
--
--   async_jobs     SQS 로 전달하는 LLM 작업. Task 당 한 건.
--   outbox_events  DB 저장과 SQS 발행 사이의 유실을 막는다.
--
--   Task·Job·Outbox 를 한 트랜잭션으로 저장하고, SQS 발행은 트랜잭션 밖의
--   전달기가 미발행 Outbox 를 읽어 처리한다.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- async_jobs
-- ---------------------------------------------------------------------------
CREATE TABLE async_jobs (
    id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             uuid        NOT NULL DEFAULT gen_random_uuid(),
    task_id               bigint      NOT NULL,

    job_type              varchar(40) NOT NULL,
    status                varchar(20) NOT NULL DEFAULT 'PENDING',

    -- 모델에 전달할 구조화 입력. 비밀값·인증 토큰을 넣지 않는다.
    input                 jsonb,
    result                jsonb,

    -- 실제 사용한 모델과 추론 소요 시간 (성능 기록)
    model                 varchar(60),
    duration_milliseconds integer,

    error_code            varchar(40),
    -- 같은 Job 을 다시 처리할 수 있는지. SQS 수신 횟수·DLQ 정책에 함께 쓴다.
    retryable             boolean,

    -- LLM 결과 메시지의 eventId. 같은 결과가 두 번 반영되는 것을 막는다.
    -- 같은 eventId 재수신은 멱등 처리하고, 다른 eventId 는 IDEMPOTENCY_CONFLICT 로 거부한다.
    result_event_id       uuid,

    attempt_count         integer     NOT NULL DEFAULT 0,

    -- 비싼 GPU 시험 작업이 무기한 남지 않도록 두는 만료 시각. LLM 작업에만 사용한다.
    deadline_at           timestamptz NOT NULL,
    started_at            timestamptz,
    completed_at          timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_async_jobs_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

    CONSTRAINT uk_async_jobs_public_id UNIQUE (public_id),

    -- P0 는 Task 당 AI Job 한 건이다.
    CONSTRAINT uk_async_jobs_task UNIQUE (task_id),

    -- 한 결과 메시지가 여러 Job 에 반영되는 것을 막는다.
    CONSTRAINT uk_async_jobs_result_event UNIQUE (result_event_id),

    CONSTRAINT ck_async_jobs_job_type
        CHECK (job_type IN ('TEXT_SUMMARY', 'SYSTEM_STATUS_EXPLANATION')),

    CONSTRAINT ck_async_jobs_status
        CHECK (status IN ('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED')),

    CONSTRAINT ck_async_jobs_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_async_jobs_deadline_after_created
        CHECK (deadline_at > created_at),

    -- 완료 시각은 최종 상태일 때만 존재한다.
    CONSTRAINT ck_async_jobs_completed_at
        CHECK ((status IN ('SUCCEEDED', 'FAILED', 'EXPIRED')) = (completed_at IS NOT NULL)),

    -- 오류 코드는 실패·만료일 때만 존재한다.
    CONSTRAINT ck_async_jobs_error_code
        CHECK (error_code IS NULL OR status IN ('FAILED', 'EXPIRED')),

    -- 성공 결과와 오류가 동시에 존재하지 않는다. (프로토콜 7.2)
    CONSTRAINT ck_async_jobs_result_or_error
        CHECK (result IS NULL OR error_code IS NULL),

    -- 결과 크기 상한. tasks.result 와 같은 기준을 적용한다.
    CONSTRAINT ck_async_jobs_result_size
        CHECK (result IS NULL OR octet_length(result::text) <= 65536)
);

CREATE TRIGGER trg_async_jobs_set_updated_at
    BEFORE UPDATE ON async_jobs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- 만료 처리 배치용.
-- 주의: 시간이 지나도 status 는 자동으로 바뀌지 않는다.
--       deadline_at 이 지난 미완료 Job 을 배치가 EXPIRED 로 마감해야
--       GPU 시험 작업이 무기한 남지 않는다.
CREATE INDEX idx_async_jobs_active_deadline
    ON async_jobs (deadline_at)
    WHERE status IN ('PENDING', 'QUEUED', 'RUNNING');

COMMENT ON TABLE  async_jobs                 IS 'SQS 로 전달하는 LLM 작업. Task 당 한 건.';
COMMENT ON COLUMN async_jobs.result_event_id IS 'LLM 결과 메시지의 eventId. 중복 결과 반영을 막는다.';
COMMENT ON COLUMN async_jobs.deadline_at     IS 'LLM·GPU 시험 운영 정리를 위한 만료 시각. 일반 REST·Agent 작업에는 적용하지 않는다.';

-- ---------------------------------------------------------------------------
-- outbox_events
--
--   DB 트랜잭션 안에서 저장하고, 전달기가 미발행 건을 읽어 SQS 로 보낸다.
--   중단 뒤 재전송되어도 수신 측 고유 제약으로 중복 처리하지 않는다.
--
--   여러 Pod 가 동시에 전달기를 돌릴 수 있으므로 조회는
--   SELECT ... FOR UPDATE SKIP LOCKED 로 한다.
-- ---------------------------------------------------------------------------
CREATE TABLE outbox_events (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      uuid         NOT NULL DEFAULT gen_random_uuid(),

    -- 어떤 원장에서 발생한 사건인지. 여러 표를 가리키므로 FK 를 두지 않는다.
    aggregate_type varchar(30)  NOT NULL,
    aggregate_id   bigint       NOT NULL,

    event_type     varchar(60)  NOT NULL,
    payload        jsonb        NOT NULL,

    attempt_count  integer      NOT NULL DEFAULT 0,

    -- 재시도 백오프에 사용한다. 이 시각 이후에만 발행 대상이 된다.
    available_at   timestamptz  NOT NULL DEFAULT now(),
    published_at   timestamptz,
    created_at     timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uk_outbox_public_id UNIQUE (public_id),

    CONSTRAINT ck_outbox_aggregate_type
        CHECK (aggregate_type IN ('TASK', 'ASYNC_JOB')),

    CONSTRAINT ck_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

-- 미발행 건 조회. 발행 완료된 행은 인덱스에서 빠져 계속 가벼운 상태를 유지한다.
CREATE INDEX idx_outbox_unpublished
    ON outbox_events (available_at, id)
    WHERE published_at IS NULL;

COMMENT ON TABLE  outbox_events              IS 'DB 저장과 SQS 발행 사이의 유실 방지. published_at IS NULL 만 전달 대상이다.';
COMMENT ON COLUMN outbox_events.aggregate_id IS '여러 원장을 가리키므로 FK 를 두지 않는다. 정합성은 서비스 계층이 보장한다.';
COMMENT ON COLUMN outbox_events.available_at IS '재시도 백오프. 이 시각 이후에만 발행 대상이 된다.';
