-- ---------------------------------------------------------------------------
-- V007 : 보안 감사
--
--   PC 등록·해제, 권한 변경 같은 주요 사건을 남긴다.
--   비밀값·전체 파일 경로·원문 IP 는 저장하지 않는다.
--
--   사용자를 지워도 감사 기록은 남아야 하므로 user_id 는 SET NULL 로 둔다.
--   (다른 표는 사용자 삭제 자체를 RESTRICT 로 막지만, 감사는 삭제 이력도 남긴다)
-- ---------------------------------------------------------------------------

CREATE TABLE audit_events (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        uuid        NOT NULL DEFAULT gen_random_uuid(),

    -- 사용자가 삭제돼도 기록은 유지한다.
    user_id          bigint,

    -- 누가 일으킨 사건인지
    actor_type       varchar(20) NOT NULL,

    -- 무슨 일이 일어났는지 (예: DEVICE_REGISTERED, DEVICE_REVOKED)
    action           varchar(60) NOT NULL,

    -- 무엇에 대한 사건인지
    target_type      varchar(30),
    target_public_id uuid,

    -- 사건별 부가 정보. 비밀값·전체 경로를 넣지 않는다.
    detail           jsonb,

    -- 원문 IP 대신 해시만 남긴다.
    ip_hash          varchar(64),

    occurred_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_audit_events_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT uk_audit_events_public_id UNIQUE (public_id),

    CONSTRAINT ck_audit_events_actor_type
        CHECK (actor_type IN ('USER', 'AGENT', 'SERVICE', 'SYSTEM')),

    CONSTRAINT ck_audit_events_target_type
        CHECK (target_type IS NULL OR target_type IN ('USER', 'DEVICE', 'TASK', 'PAIRING_REQUEST')),

    -- 대상 종류와 식별자는 함께 있거나 함께 없어야 한다.
    CONSTRAINT ck_audit_events_target
        CHECK ((target_type IS NULL) = (target_public_id IS NULL))
);

-- 사용자별 감사 조회
CREATE INDEX idx_audit_user_time ON audit_events (user_id, occurred_at DESC);

-- 대상 자원 기준 추적 (예: 특정 PC 의 등록·해제 이력)
CREATE INDEX idx_audit_target ON audit_events (target_type, target_public_id, occurred_at DESC)
    WHERE target_type IS NOT NULL;

COMMENT ON TABLE  audit_events         IS 'PC 등록 해제·권한 등 주요 변경 기록. 비밀값과 전체 파일 경로를 저장하지 않는다.';
COMMENT ON COLUMN audit_events.user_id IS '사용자가 삭제돼도 기록은 남기기 위해 SET NULL 로 둔다.';
COMMENT ON COLUMN audit_events.ip_hash IS '원문 IP 대신 해시. 개인정보 최소 수집 원칙.';
