-- ---------------------------------------------------------------------------
-- V014 : 사용자 확인이 필요한 작업의 승인 단계 (P0-C · 계획 문서 §1.5)
--
--   지금은 승인이 필요한 작업이 하나도 없다. 문서 §1.4 가 "패치 적용, 시험 명령 실행,
--   임의 코드 수정은 별도 승인 정책이 완성되기 전에는 포함하지 않는다" 고 못박았고,
--   §12.2 는 "승인형 파일·코드 변경" 을 조건부 승인으로 두었다.
--
--   그래서 이것은 기능이 아니라 **기반**이다. 승인이 필요한 작업이 생겼을 때 그 유형을
--   설정에 넣으면 곧바로 돈다. (slash.approval.required-task-types)
-- ---------------------------------------------------------------------------

CREATE TABLE task_approvals (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        uuid        NOT NULL DEFAULT gen_random_uuid(),

    -- 작업당 승인은 하나다. 다시 물으려면 새 작업으로 접수한다.
    task_id          bigint      NOT NULL,

    status           varchar(20) NOT NULL DEFAULT 'PENDING',

    -- ---------------------------------------------------------------------
    -- 승인한 것과 실행되는 것이 같은지 확인하는 값.
    --
    --   사용자가 본 내용과 다른 것이 실행되면 승인은 뜻을 잃는다. 승인 시점의 입력값을
    --   해시로 굳혀 두고 실행 직전에 다시 계산해 맞춘다.
    --
    --   지금 구조에서는 그 사이에 입력값이 바뀔 길이 없다. 그래도 두는 이유는, 이 값이
    --   없으면 나중에 "승인 뒤 입력을 고칠 수 있게" 바꾸는 순간 아무도 알아채지 못하기
    --   때문이다. 계약으로 굳혀 둔다.
    -- ---------------------------------------------------------------------
    parameters_hash  varchar(64) NOT NULL,

    -- 사용자 응답 기한. 지나면 스윕이 만료로 마감한다.
    expires_at       timestamptz NOT NULL,

    -- 결정한 시각과 사람. 감사 기록과 짝을 이룬다.
    decided_at       timestamptz,
    decided_by       bigint,

    -- 같은 승인을 두 번 처리하지 않기 위한 값. If-Match 로 받는다.
    -- (기기 수신 중지·해제와 같은 방식)
    version          integer     NOT NULL DEFAULT 0,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_task_approvals_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,

    -- 결정한 사람은 지워져도 승인 기록은 남는다. (audit_events 와 같은 판단)
    CONSTRAINT fk_task_approvals_decided_by
        FOREIGN KEY (decided_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT uk_task_approvals_public_id UNIQUE (public_id),

    -- 한 작업에 승인은 하나뿐이다.
    CONSTRAINT uk_task_approvals_task UNIQUE (task_id),

    CONSTRAINT ck_task_approvals_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')),

    -- 결정한 것에는 시각과 사람이 있고, 기다리는 것에는 없다.
    -- 사람은 탈퇴하면 비므로 시각만 본다.
    CONSTRAINT ck_task_approvals_decided_at
        CHECK ((status IN ('APPROVED', 'REJECTED')) = (decided_at IS NOT NULL)),

    -- 기한은 만든 뒤여야 한다. (async_jobs 의 같은 제약과 나란히 둔다)
    CONSTRAINT ck_task_approvals_expires_after_created
        CHECK (expires_at > created_at)
);

CREATE TRIGGER trg_task_approvals_updated_at
    BEFORE UPDATE ON task_approvals
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 기한이 지난 승인을 찾는 스윕이 쓴다.
CREATE INDEX idx_task_approvals_pending_expiry
    ON task_approvals (expires_at)
    WHERE status = 'PENDING';

-- ---------------------------------------------------------------------------
-- 새 작업 상태 : WAITING_FOR_APPROVAL
--
--   분석을 마친 뒤 실행하기 전에 사용자에게 묻는 자리다. 승인하면 원래 가려던 경로로
--   이어지고, 거절하면 실패로, 답이 없으면 기한이 지나 만료로 마감한다.
-- ---------------------------------------------------------------------------

ALTER TABLE tasks
    DROP CONSTRAINT ck_tasks_status;

ALTER TABLE tasks
    ADD CONSTRAINT ck_tasks_status
        CHECK (status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION', 'WAITING_FOR_APPROVAL',
                          'WAITING_FOR_DEVICE', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED'));

-- ---------------------------------------------------------------------------
-- 타임라인도 새 상태를 받을 수 있어야 한다.
--
--   tasks 만 풀면 상태는 바뀌는데 그 전이를 기록하지 못해 저장에서 터진다. 상태 값을
--   세어 둔 곳이 세 군데(tasks·task_events 둘)라, 하나만 고치면 조용히 어긋난다.
-- ---------------------------------------------------------------------------

ALTER TABLE task_events
    DROP CONSTRAINT ck_task_events_from_status;

ALTER TABLE task_events
    ADD CONSTRAINT ck_task_events_from_status
        CHECK (from_status IS NULL OR from_status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION',
               'WAITING_FOR_APPROVAL', 'WAITING_FOR_DEVICE', 'QUEUED', 'RUNNING',
               'SUCCEEDED', 'FAILED', 'EXPIRED'));

ALTER TABLE task_events
    DROP CONSTRAINT ck_task_events_to_status;

ALTER TABLE task_events
    ADD CONSTRAINT ck_task_events_to_status
        CHECK (to_status IN ('CREATED', 'ANALYZING', 'NEEDS_CLARIFICATION', 'WAITING_FOR_APPROVAL',
               'WAITING_FOR_DEVICE', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED'));
